name: Deploy to gh-pages

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - '.github/workfows/gh-pages-deploy.yml'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          persisit-credentials: false
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: RekiGit
          git-config-email: RekiAction@users.noreply.github.com
          branch: gh-pages
          folder: build
          single-comit: true
